package ee.twentyten.util;

import ee.twentyten.config.LauncherConfigImpl;
import java.util.UUID;
import lombok.Getter;
import lombok.Setter;

public final class ConfigUtils {

  @Getter
  @Setter
  private static LauncherConfigImpl instance;

  static {
    ConfigUtils.setInstance(new LauncherConfigImpl());
  }

  private ConfigUtils() {
    throw new UnsupportedOperationException("Can't instantiate utility class");
  }

  public static String generateConfigFileHeader() {
    return new StringBuilder().append("##################################################")
        .append(SystemUtils.lineSeparator)
        .append("##    TwentyTen Launcher Configuration File     ##")
        .append(SystemUtils.lineSeparator)
        .append("##==============================================##")
        .append(SystemUtils.lineSeparator)
        .append("##    This file is automatically generated by   ##")
        .append(SystemUtils.lineSeparator)
        .append("##    the launcher. Do not modify this file.    ##")
        .append(SystemUtils.lineSeparator)
        .append("##################################################")
        .append(SystemUtils.lineSeparator).toString();
  }

  public static String generateClientToken() {
    return UUID.randomUUID().toString().replace("-", "");
  }

  public static String formatSessionId(String clientToken, String accessToken, String uuid) {
    return new StringBuilder().append(clientToken).append(":").append(accessToken).append(":")
        .append(uuid).toString();
  }

  public static void loadConfig() {
    ConfigUtils.getInstance().load();
  }

  public static void saveConfig() {
    ConfigUtils.getInstance().save();
  }
}
