package ee.twentyten.util;

import ee.twentyten.config.LauncherConfigImpl;
import java.util.UUID;
import lombok.Getter;

public final class ConfigUtils {

  @Getter
  public static LauncherConfigImpl config;

  static {
    ConfigUtils.config = new LauncherConfigImpl();
  }

  private ConfigUtils() {
    throw new UnsupportedOperationException("Can't instantiate utility class");
  }

  public static String generateConfigFileHeader() {
    return new StringBuilder().append("##################################################")
        .append(SystemUtils.lineSeparator)
        .append("##    TwentyTen Launcher Configuration File     ##")
        .append(SystemUtils.lineSeparator)
        .append("##==============================================##")
        .append(SystemUtils.lineSeparator)
        .append("##    This file is automatically generated by   ##")
        .append(SystemUtils.lineSeparator)
        .append("##    the launcher. Do not modify this file.    ##")
        .append(SystemUtils.lineSeparator)
        .append("##################################################")
        .append(SystemUtils.lineSeparator).toString();
  }

  public static String generateClientToken() {
    return UUID.randomUUID().toString().replace("-", "");
  }

  public static String formatSessionId(String clientToken, String accessToken, String uuid) {
    return String.format("%s:%s:%s", clientToken, accessToken, uuid);
  }

  public static void loadConfig() {
    ConfigUtils.getConfig().load();
  }

  public static void saveConfig() {
    ConfigUtils.getConfig().save();
  }
}
