/*
 * Copyright (C) 2023 Kawaxte
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * program. If not, see <https://www.gnu.org/licenses/>.
 */

package ch.kawaxte.launcher.util;

import ch.kawaxte.launcher.LauncherConfig;
import ch.kawaxte.launcher.auth.YggdrasilAuth;
import ch.kawaxte.launcher.auth.YggdrasilAuthWorker;
import java.util.Objects;

/**
 * Utility class for handling Mojang (Yggdrasil) authentication.
 *
 * <p>Note that this class is a singleton, and thus cannot be instantiated directly.
 *
 * @author Kawaxte
 * @since 1.5.0623_01
 */
public final class YggdrasilAuthUtils {

  private YggdrasilAuthUtils() {}

  /**
   * Executes the Yggdrasil authentication worker with the given parameters.
   *
   * <p>It also sets the configuration values for username, password, and rememberPasswordChecked.
   * They will be saved during the execution of the worker.
   *
   * @param username username of the account (or email address if Mojang account)
   * @param password password of the account
   * @param clientToken a random UUID (version 4) generated by the launcher
   * @param rememberPasswordChecked whether the password should be remembered or not
   */
  public static void executeYggdrasilAuthWorker(
      String username, String password, String clientToken, boolean rememberPasswordChecked) {
    if ((Objects.isNull(username) || Objects.isNull(password) || Objects.isNull(clientToken))) {
      throw new NullPointerException("username, password, or clientToken cannot be null");
    }
    if (clientToken.isEmpty()) {
      throw new IllegalArgumentException("clientToken cannot be empty");
    }

    LauncherConfig.set(11, username);
    LauncherConfig.set(12, rememberPasswordChecked ? LauncherUtils.encodeToBase64(password) : "");
    LauncherConfig.set(13, rememberPasswordChecked);

    new YggdrasilAuthWorker(username, password, clientToken).execute();
  }

  /**
   * Checks if the access token is expired as long as both the access token and the client token are
   * not {@code null} or empty.
   *
   * @see YggdrasilAuth#validate(String, String)
   */
  public static void isAccessTokenExpired() {
    String accessToken = (String) LauncherConfig.get(17);
    String clientToken = (String) LauncherConfig.get(18);
    if (Objects.isNull(accessToken) || Objects.isNull(clientToken)) {
      return;
    }
    if (accessToken.isEmpty() || clientToken.isEmpty()) {
      return;
    }

    YggdrasilAuth.validate(accessToken, clientToken);
  }
}
