blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Kawaxte/TwentyTenLauncher/discussions
    about: Please discuss with us on GitHub Discussions before opening an issue.