name: Suggestion

about: Have a suggestion for TwentyTen Launcher? Let us know!

labels:
  - suggestion

body:
  - type: markdown
    attributes:
      value: |
        ## Suggestion
        Please describe your suggestion for TwentyTen Launcher below.

  - type: input
    id: suggestion_title
    attributes:
      label: Title
      description: Give your suggestion a clear and descriptive title. (up to 80 characters)
      placeholder: e.g "Add X to the launcher"
      validate:
        required: true
        max-length: 80

  - type: textarea
    id: suggestion_description
    attributes:
      label: Description
      description: Please provide a detailed description of your suggestion. (up to 2000 characters)
      placeholder: e.g "I think X should be added to the launcher because..."
      validate:
        required: true
        max-length: 2000

  - type: radio
    id: suggestion_type
    attributes:
      label: Type
      description: Is your Minecraft client vanilla or modded?
      options:
        - Vanilla
        - Modded
      validate:
        required: true

  - type: dropdown
    id: suggestion_version
    attributes:
      label: Version
      description: What version of Minecraft is your suggestion related to?
      placeholder: e.g "Beta 1.1_02"
      multiple: false
      options:
        - Beta 1.8.1
        - Beta 1.8
        - Beta 1.7.3
        - Beta 1.7.2
        - Beta 1.7_01
        - Beta 1.7
        - Beta 1.6.6
        - Beta 1.6.5
        - Beta 1.6.4
        - Beta 1.6.3
        - Beta 1.6.2
        - Beta 1.6.1
        - Beta 1.6
        - Beta 1.5_01
        - Beta 1.5
        - Beta 1.4_01
        - Beta 1.4
        - Beta 1.3_01
        - Beta 1.3
        - Beta 1.2_02
        - Beta 1.2_01
        - Beta 1.2
        - Beta 1.1_02
        - Beta 1.1_01
        - Beta 1.1
        - Beta 1.0.2
        - Beta 1.0_01
        - Beta 1.0
        - Alpha v1.2.6
        - Alpha v1.2.5
        - Alpha v1.2.4_01
        - Alpha v1.2.3_05
        - Alpha v1.2.3_04
        - Alpha v1.2.3_02
        - Alpha v1.2.3_01
        - Alpha v1.2.3
        - Alpha v1.2.2
        - Alpha v1.2.1_01
        - Alpha v1.2.0_02
        - Alpha v1.2.0_01
        - Alpha v1.2.0
        - Alpha v1.1.2_01
        - Alpha v1.1.2
        - Alpha v1.1.1
        - Alpha v1.1.0
        - Alpha v1.0.17_04
        - Alpha v1.0.17_03
        - Alpha v1.0.17_02
        - Alpha v1.0.16_02
        - Alpha v1.0.16_01
        - Alpha v1.0.16
        - Alpha v1.0.15
        - Alpha v1.0.14
        - Alpha v1.0.13_01
        - Alpha v1.0.13
        - Alpha v1.0.12
        - Alpha v1.0.11
        - Alpha v1.0.10
        - Alpha v1.0.9
        - Alpha v1.0.8_01
        - Alpha v1.0.7
        - Alpha v1.0.6_03
        - Alpha v1.0.6_01
        - Alpha v1.0.6
        - Alpha v1.0.5_01
        - Alpha v1.0.5
        - Alpha v1.0.4
        - Alpha v1.0.3
        - Alpha v1.0.2_02
        - Alpha v1.0.2_01
        - Alpha v1.0.1_01
        - Alpha v1.0.0
        - Infdev (Jun 30, 2010)
        - Infdev (Jun 29, 2010)
        - Infdev (Jun 27, 2010)
        - Infdev (Jun 25, 2010)
        - Infdev (Jun 24, 2010)
        - Infdev (Jun 18, 2010)
        - Infdev (Jun 17, 2010)
        - Infdev (Jun 16, 2010)
        - Infdev (Jun 15, 2010)
        - Infdev (Jun 11, 2010)
        - Infdev (Jun 8, 2010)
        - Infdev (Jun 7, 2010)
        - Infdev (Apr 20, 2010)
        - Infdev (Apr 15, 2010)
        - Infdev (Apr 14, 2010)
        - Infdev (Apr 13, 2010)
        - Infdev (Mar 30, 2010)
        - Infdev (Mar 27, 2010)
        - Infdev (Mar 25, 2010)
        - Infdev (Mar 21, 2010)
        - Infdev (Mar 20, 2010)
        - Infdev (Mar 16, 2010)
        - Infdev (Mar 13, 2010)
        - Infdev (Feb 27, 2010)
      validate:
        required: true

  - type: checkboxes
    id: suggestion_confirm
    attributes:
      label: Confirmation
      description:
        By submitting this suggestion, I confirm that:
      options:
        - I have read the CONTRIBUTING guidelines.
        - I have searched for duplicate suggestions in both open and closed issues.
      validate:
        required: true

  - type: submit
    attributes:
      label: Submit Suggestion