/*
 * Copyright (C) 2023 Kawaxte
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * program. If not, see <https://www.gnu.org/licenses/>.
 */

package io.github.kawaxte.twentyten.launcher.util;

import io.github.kawaxte.twentyten.launcher.LauncherConfig;
import io.github.kawaxte.twentyten.launcher.auth.YggdrasilAuth;
import io.github.kawaxte.twentyten.launcher.auth.YggdrasilAuthWorker;
import io.github.kawaxte.twentyten.launcher.exception.AuthenticationException;
import java.util.Objects;
import org.json.JSONObject;

/**
 * Utility class for handling Mojang (Yggdrasil) authentication.
 *
 * @author Kawaxte
 * @since 1.5.0623_01
 */
public final class YggdrasilAuthUtils {

  private YggdrasilAuthUtils() {}

  /**
   * Executes the Yggdrasil authentication worker with the given parameters.
   *
   * <p>It also sets the configuration values for username, password, and rememberPasswordChecked.
   * They will be saved during the execution of the worker.
   *
   * @param username username of the account (or email address if Mojang account)
   * @param password password of the account
   * @param clientToken a random UUID (version 4) generated by the launcher
   * @param rememberPasswordChecked whether the password should be remembered or not
   */
  public static void executeYggdrasilAuthWorker(
      String username, String password, String clientToken, boolean rememberPasswordChecked) {
    if ((Objects.isNull(username) || Objects.isNull(password) || Objects.isNull(clientToken))) {
      throw new NullPointerException("username, password, or clientToken cannot be null");
    }
    if (clientToken.isEmpty()) {
      throw new IllegalArgumentException("clientToken cannot be empty");
    }

    LauncherConfig.set(11, username);
    LauncherConfig.set(12, rememberPasswordChecked ? LauncherUtils.encodeToBase64(password) : "");
    LauncherConfig.set(13, rememberPasswordChecked);

    new YggdrasilAuthWorker(username, password, clientToken).execute();
  }

  /**
   * Checks if the access token is expired as long as both the access token and the client token are
   * not {@code null} or empty.
   *
   * @return {@code true} if the access token is expired, {@code false} otherwise
   * @see io.github.kawaxte.twentyten.launcher.auth.YggdrasilAuth#validateAccessToken(String,
   *     String)
   */
  public static boolean isAccessTokenExpired() {
    String accessToken = (String) LauncherConfig.get(17);
    String clientToken = (String) LauncherConfig.get(18);
    if (Objects.isNull(accessToken) || Objects.isNull(clientToken)) {
      return false;
    }
    if (accessToken.isEmpty() || clientToken.isEmpty()) {
      return false;
    }

    JSONObject validate = YggdrasilAuth.validateAccessToken(accessToken, clientToken);
    return !Objects.isNull(validate) && validate.has("error");
  }

  /**
   * Refreshes the expired access token and saves it to the configuration file.
   *
   * @throws AuthenticationException if the access token cannot be refreshed
   * @see io.github.kawaxte.twentyten.launcher.auth.YggdrasilAuth#refreshAccessToken(String, String)
   */
  public static void refreshAccessToken() {
    String accessToken = (String) LauncherConfig.get(17);
    String clientToken = (String) LauncherConfig.get(18);

    JSONObject refresh = YggdrasilAuth.refreshAccessToken(accessToken, clientToken);
    if (Objects.isNull(refresh)) {
      return;
    }
    if (refresh.has("error")) {
      throw new AuthenticationException("Cannot refresh access token");
    }

    String newAccessToken = refresh.getString("accessToken");
    LauncherConfig.set(17, newAccessToken);
    LauncherConfig.saveConfig();
  }
}
