name: Google Java Format

on:
  push:
    branches: [ stable , nightly ]

jobs:
  formatting:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"